In [3]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
mpl.style.use('ggplot')
import warnings
warnings.filterwarnings("ignore")

In [4]:
car=pd.read_csv('final_data.csv')

In [5]:
car.rename(columns={'Registered City': 'Registered_City'}, inplace=True)

In [6]:
car.head()

Make    Model                          Version      Price  Make_Year  \
0  Mitsubishi   Minica                     Black Minica  1065000.0       2019   
1        Audi       A6  1.8 TFSI Business Class Edition  9300000.0       2015   
2      Toyota     Aqua                                G  2375000.0       2014   
3       Honda     City                       1.3 i-VTEC  2600000.0       2017   
4      Toyota  Corolla           GLi Automatic 1.3 VVTi  2500000.0       2017   

     CC  Assembly  Mileage Registered_City Transmission  
0   660  Imported    68000          Lahore    Automatic  
1  1800     Local    70000          Lahore    Automatic  
2  1500  Imported    99900       Islamabad    Automatic  
3  1300     Local    55000       Islamabad       Manual  
4  1300     Local    80000          Lahore    Automatic

In [7]:
car.shape

(72644, 10)

In [8]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72644 entries, 0 to 72643
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Make             72644 non-null  object 
 1   Model            72644 non-null  object 
 2   Version          72644 non-null  object 
 3   Price            72644 non-null  float64
 4   Make_Year        72644 non-null  int64  
 5   CC               72644 non-null  int64  
 6   Assembly         72644 non-null  object 
 7   Mileage          72644 non-null  int64  
 8   Registered_City  72644 non-null  object 
 9   Transmission     72644 non-null  object 
dtypes: float64(1), int64(3), object(6)
memory usage: 5.5+ MB


In [9]:
car['Version']

0                           Black Minica
1        1.8 TFSI Business Class Edition
2                                      G
3                             1.3 i-VTEC
4                 GLi Automatic 1.3 VVTi
                      ...               
72639                GLi 1.3 VVTi Ecotec
72640                                VXR
72641             GLi Automatic 1.3 VVTi
72642                           Standard
72643           VTi Prosmatec 1.8 i-VTEC
Name: Version, Length: 72644, dtype: object

In [10]:
car['Price']

0        1065000.0
1        9300000.0
2        2375000.0
3        2600000.0
4        2500000.0
           ...    
72639    2100000.0
72640    1480000.0
72641    2700000.0
72642     600000.0
72643    2620000.0
Name: Price, Length: 72644, dtype: float64

In [11]:
car['Price'] = car['Price'].astype(int)


In [12]:
car['Price']

0        1065000
1        9300000
2        2375000
3        2600000
4        2500000
          ...   
72639    2100000
72640    1480000
72641    2700000
72642     600000
72643    2620000
Name: Price, Length: 72644, dtype: int64

In [13]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72644 entries, 0 to 72643
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Make             72644 non-null  object
 1   Model            72644 non-null  object
 2   Version          72644 non-null  object
 3   Price            72644 non-null  int64 
 4   Make_Year        72644 non-null  int64 
 5   CC               72644 non-null  int64 
 6   Assembly         72644 non-null  object
 7   Mileage          72644 non-null  int64 
 8   Registered_City  72644 non-null  object
 9   Transmission     72644 non-null  object
dtypes: int64(4), object(6)
memory usage: 5.5+ MB


In [14]:
car.describe()

Price     Make_Year            CC        Mileage
count  7.264400e+04  72644.000000  72644.000000   72644.000000
mean   2.595503e+06   2011.848109   1402.504309   85983.507227
std    3.780795e+06      6.755071    668.776710   81548.660604
min    1.000000e+05   1990.000000    600.000000       1.000000
25%    9.750000e+05   2007.000000   1000.000000   38000.000000
50%    1.750000e+06   2014.000000   1300.000000   73500.000000
75%    2.900000e+06   2017.000000   1600.000000  110803.500000
max    9.500000e+07   2021.000000   6600.000000  999999.000000

In [15]:
car=car[car['Price']<8.5e7].reset_index(drop=True)

In [16]:
car

Make    Model                          Version    Price  \
0      Mitsubishi   Minica                     Black Minica  1065000   
1            Audi       A6  1.8 TFSI Business Class Edition  9300000   
2          Toyota     Aqua                                G  2375000   
3           Honda     City                       1.3 i-VTEC  2600000   
4          Toyota  Corolla           GLi Automatic 1.3 VVTi  2500000   
...           ...      ...                              ...      ...   
72638      Toyota  Corolla              GLi 1.3 VVTi Ecotec  2100000   
72639      Suzuki     Alto                              VXR  1480000   
72640      Toyota  Corolla           GLi Automatic 1.3 VVTi  2700000   
72641         FAW     X-PV                         Standard   600000   
72642       Honda    Civic         VTi Prosmatec 1.8 i-VTEC  2620000   

       Make_Year    CC  Assembly  Mileage Registered_City Transmission  
0           2019   660  Imported    68000          Lahore    Automatic  
1           2015  1800     Local    70000          Lahore    Automatic  
2           2014  1500  Imported    99900       Islamabad    Automatic  
3           2017  1300     Local    55000       Islamabad       Manual  
4           2017  1300     Local    80000          Lahore    Automatic  
...          ...   ...       ...      ...             ...          ...  
72638       2012  1300     Local   125000         Karachi       Manual  
72639       2020   660     Local     7800         Karachi       Manual  
72640       2016  1300     Local    81000       Islamabad    Automatic  
72641       2013  1000     Local        2          Lahore       Manual  
72642       2013  1800  Imported   100000       Islamabad    Automatic  

[72643 rows x 10 columns]

In [17]:
car[car['Price']>8.5e7]

Empty DataFrame
Columns: [Make, Model, Version, Price, Make_Year, CC, Assembly, Mileage, Registered_City, Transmission]
Index: []

In [18]:
car.to_csv('Cleaned_Car_data.csv')

## MODEL

In [19]:
X = car.drop(columns='Price')
y = car['Price']

In [20]:
X

Make    Model                          Version  Make_Year    CC  \
0      Mitsubishi   Minica                     Black Minica       2019   660   
1            Audi       A6  1.8 TFSI Business Class Edition       2015  1800   
2          Toyota     Aqua                                G       2014  1500   
3           Honda     City                       1.3 i-VTEC       2017  1300   
4          Toyota  Corolla           GLi Automatic 1.3 VVTi       2017  1300   
...           ...      ...                              ...        ...   ...   
72638      Toyota  Corolla              GLi 1.3 VVTi Ecotec       2012  1300   
72639      Suzuki     Alto                              VXR       2020   660   
72640      Toyota  Corolla           GLi Automatic 1.3 VVTi       2016  1300   
72641         FAW     X-PV                         Standard       2013  1000   
72642       Honda    Civic         VTi Prosmatec 1.8 i-VTEC       2013  1800   

       Assembly  Mileage Registered_City Transmission  
0      Imported    68000          Lahore    Automatic  
1         Local    70000          Lahore    Automatic  
2      Imported    99900       Islamabad    Automatic  
3         Local    55000       Islamabad       Manual  
4         Local    80000          Lahore    Automatic  
...         ...      ...             ...          ...  
72638     Local   125000         Karachi       Manual  
72639     Local     7800         Karachi       Manual  
72640     Local    81000       Islamabad    Automatic  
72641     Local        2          Lahore       Manual  
72642  Imported   100000       Islamabad    Automatic  

[72643 rows x 9 columns]

In [21]:
y

0        1065000
1        9300000
2        2375000
3        2600000
4        2500000
          ...   
72638    2100000
72639    1480000
72640    2700000
72641     600000
72642    2620000
Name: Price, Length: 72643, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [24]:
ohe=OneHotEncoder()
ohe.fit(X[['Make','Model','Version','Assembly','Registered_City','Transmission']])

OneHotEncoder()

In [25]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['Make','Model','Version','Assembly','Registered_City','Transmission']),
                                    remainder='passthrough')

In [26]:
lr=LinearRegression()

In [27]:
pipe=make_pipeline(column_trans,lr)

In [28]:
pipe.fit(X_train,y_train)


Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi', 'BMW', 'Cadillac', 'Changan', 'Chery', 'Chevrolet',
       'Chrysler', 'DFSK', 'Daehan', 'Daewoo', 'Daihatsu', 'Datsun',
       'FAW', 'Fiat', 'Ford', 'Golden', 'Hino', 'Honda', 'Hummer',
       'Hyundai', 'Isuzu', 'JAC', 'JMC', 'JW', 'Jaguar',...
       'Tandiliyawala', 'Tando Allah Yar', 'Tando Muhammad Khan',
       'Taxila', 'Thatta', 'Toba Tek Singh', 'Umer Kot', 'Un-Registered',
       'Vehari', 'Wah cantt', 'Warburton', 'Wazirabad', 'Yazman mandi',
       'Zafarwal'], dtype=object),
                                                                            array(['Automatic', 'Manual'], dtype=object)]),
                                                  ['Make', 'Model', 'Version',
                                                   'Assembly',
                                                   'Registered_City',
                                                   'Transmission'])])),
                ('linearregression', LinearRegression())])

In [38]:
y_pred=pipe.predict(X_test)


In [39]:
r2_score(y_test,y_pred)

0.6348730477815463

In [31]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    scores.append(r2_score(y_test,y_pred))


In [40]:
np.argmax(scores)

859

In [41]:
scores[np.argmax(scores)]

0.6348730477815463

In [42]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.6348730477815463

In [42]:
import joblib


In [43]:
joblib.dump(pipe,open('LinearRegressionModel.joblib','wb'))

In [43]:
car

Make    Model                          Version    Price  \
0      Mitsubishi   Minica                     Black Minica  1065000   
1            Audi       A6  1.8 TFSI Business Class Edition  9300000   
2          Toyota     Aqua                                G  2375000   
3           Honda     City                       1.3 i-VTEC  2600000   
4          Toyota  Corolla           GLi Automatic 1.3 VVTi  2500000   
...           ...      ...                              ...      ...   
72638      Toyota  Corolla              GLi 1.3 VVTi Ecotec  2100000   
72639      Suzuki     Alto                              VXR  1480000   
72640      Toyota  Corolla           GLi Automatic 1.3 VVTi  2700000   
72641         FAW     X-PV                         Standard   600000   
72642       Honda    Civic         VTi Prosmatec 1.8 i-VTEC  2620000   

       Make_Year    CC  Assembly  Mileage Registered_City Transmission  
0           2019   660  Imported    68000          Lahore    Automatic  
1           2015  1800     Local    70000          Lahore    Automatic  
2           2014  1500  Imported    99900       Islamabad    Automatic  
3           2017  1300     Local    55000       Islamabad       Manual  
4           2017  1300     Local    80000          Lahore    Automatic  
...          ...   ...       ...      ...             ...          ...  
72638       2012  1300     Local   125000         Karachi       Manual  
72639       2020   660     Local     7800         Karachi       Manual  
72640       2016  1300     Local    81000       Islamabad    Automatic  
72641       2013  1000     Local        2          Lahore       Manual  
72642       2013  1800  Imported   100000       Islamabad    Automatic  

[72643 rows x 10 columns]

In [44]:
pipe.predict(pd.DataFrame([['Honda','Civic','VTi Prosmatec 1.8 i-VTEC',2013,1800,'Imported',100000,'Islamabad','Automatic']], columns=['Make','Model','Version','Make_Year','CC','Assembly','Mileage','Registered_City','Transmission']))

array([3823457.70728499])

In [45]:
pipe.predict(pd.DataFrame([['Suzuki','Alto','VXR',2018,660,'Local',78,'Karachi','Manual']], columns=['Make','Model','Version','Make_Year','CC','Assembly','Mileage','Registered_City','Transmission']))

array([1261342.12851208])

In [46]:
pipe.steps[0][1].transformers[0][1].categories[0]


array(['Audi', 'BMW', 'Cadillac', 'Changan', 'Chery', 'Chevrolet',
       'Chrysler', 'DFSK', 'Daehan', 'Daewoo', 'Daihatsu', 'Datsun',
       'FAW', 'Fiat', 'Ford', 'Golden', 'Hino', 'Honda', 'Hummer',
       'Hyundai', 'Isuzu', 'JAC', 'JMC', 'JW', 'Jaguar', 'Jeep', 'KIA',
       'Land', 'Lexus', 'MG', 'MINI', 'Master', 'Mazda', 'Mercedes',
       'Mitsubishi', 'Nissan', 'Porsche', 'Prince', 'Proton', 'Range',
       'Roma', 'Sogo', 'Sokon', 'SsangYong', 'Subaru', 'Suzuki', 'Tesla',
       'Toyota', 'United', 'Volkswagen', 'Volvo', 'ZOTYE'], dtype=object)

In [47]:
pipe.predict(pd.DataFrame([['Suzuki','Alto','VXR',2018,660,'Local',78,'Karachi','Manual']], columns=['Make','Model','Version','Make_Year','CC','Assembly','Mileage','Registered_City','Transmission']))

array([1261342.12851208])

In [48]:
car.head()

Make    Model                          Version    Price  Make_Year  \
0  Mitsubishi   Minica                     Black Minica  1065000       2019   
1        Audi       A6  1.8 TFSI Business Class Edition  9300000       2015   
2      Toyota     Aqua                                G  2375000       2014   
3       Honda     City                       1.3 i-VTEC  2600000       2017   
4      Toyota  Corolla           GLi Automatic 1.3 VVTi  2500000       2017   

     CC  Assembly  Mileage Registered_City Transmission  
0   660  Imported    68000          Lahore    Automatic  
1  1800     Local    70000          Lahore    Automatic  
2  1500  Imported    99900       Islamabad    Automatic  
3  1300     Local    55000       Islamabad       Manual  
4  1300     Local    80000          Lahore    Automatic

In [58]:
pipe.predict(pd.DataFrame([['Suzuki','Alto','VXR',2018,660,'Local',78,'Karachi','Manual']], columns=['Make','Model','Version','Make_Year','CC','Assembly','Mileage','Registered_City','Transmission']))

array([1261342.12851208])

In [60]:
   car = car.drop(['Version'], axis=1)

In [61]:
car.to_csv('Tobe_Car_data.csv')

In [62]:
# Assuming `pipe` is your trained pipeline including data preprocessing and model
input_data = pd.DataFrame({
    'Make': ['Suzuki'],
    'Model': ['Alto'],
    'Make_Year': [2018],
    'CC': [660],
    'Assembly': ['Local'],
    'Mileage': [78],
    'Registered_City': ['Karachi'],
    'Transmission': ['Manual']
})

# Make predictions using the trained pipeline
prediction = pipe.predict(input_data)

# Display the predicted price
print("The predicted price is Rs", round(prediction[0], 2))


ValueError: columns are missing: {'Version'}